### ISSUE TITLE
Theme Settings will not update, Navigation Menus not displaying/working properly

### ISSUE THREAD

**Issue by AZBGSR** [wpexplorer/earth-wordpress-theme#1]
My issues just occurred recently.
I can't update the Theme settings. I can navigate to all the Theme setting tabs from my dashboard, but when I click on Save, nothing happens. No errors are generated, it just sits there.

Also, the main menu that displays at the top of the page, only displays on the Home page on a mobile device. When I navigate to another page from Home, no menu displays on the page at all. I had to add the menu in the footer in order to navigate on a mobile, which I didn't before.

On a desktop, the entire top-level navigation displays on the top of all pages, but any sub-pages that I should be able to use drop-down to navigate to only work on the Home page, not other pages.

Everything else appears to working ok.  I purchased this theme just a couple years ago and spent a lot of time getting it set up for this non-profit organization. I really don't have the budget or time to start all over looking for a different theme right now so I'm hoping to receive a patch of some kind.

**Comment by wpexplorer** [comment]
@AZBGSR Can you share the URL? Or at least let me know what version you are using? I'm happy to assist as needed so we can get things working correctly again. I'm not having those issues when testing myself.

Now, the Theme Settings does use AJAX so you wouldn't see any errors, but you should be able to check the server error logs file to see if there is an error in there, it would be very helpful.

**Comment by AZBGSR** [comment]
https://arizonabiggamesuperraffle.com/

 

When on the Home page, the top menu navigation all works fine. Try going to this page https://arizonabiggamesuperraffle.com/2020-results/ and if you are viewing on the desktop, try to click on the drop down menu for “About the Raffle” and you can’t get to the subpages from here. 

 

When you are viewing on a mobile device, the top menu only displays on the Home page. It used to also display on any sub page. Now there is no way to navigate the site once leaving the Home page without hitting a back button to go back Home. To take care of that for now I added a menu to the footer which works fine, but I didn’t need this before.

 

On the admin side, when I try to update the Theme Settings, I can view all of the settings, but I can’t change any of them. Here is a screen shot of the Styling options. It is displaying what they are currently set to, but I can’t click on any of them to change anything. I can display all the different settings tabs, but can’t edit.



 

I’m a novice, so I’m not sure where to look for server error logs. I’m not getting any error messages, just functionality is missing.  Our site goes somewhat dormant usually at the end of July until in the Fall so I’m not sure when this started happening. I have been getting it ready for our next campaign, so this is when I noticed it.

Thanks for any assistance you can give.

**Comment by AZBGSR** [comment]
Just discovered the FAQ feature is also not working now. I have a series of them on my site here:
https://arizonabiggamesuperraffle.com/frequently-asked-questions/

 

Click on any of the questions and the answer does not pop up. Nothing happens.
