### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by vskaarthi** [wpexplorer/earth-wordpress-theme#4]
Hi Team,

Can you please make the shortcodes available with the theme in Wiki or somewhere for this theme? 

Basically asking the demo site that was used to display in Themeforest.

This would help us see the features and shortcodes available to use in our projects.

Thank you.

**Comment by wpexplorer** [comment]
@vskaarthi - If you are using the WPBakery page builder all the "shortcodes" are available in the builder.

I can't make sample data available because the demo doesn't exist. Here is the old xlm but it won't download any pictures since there isn't any live demo anymore: https://a.cl.ly/OAuJwOyv

- AJ

**Comment by wpexplorer** [comment]
Note: I wouldn't recommend using the theme in any new projects since it is deprecated. The purpose of this repository is for old sites using the theme that can't or don't want to switch.

**Comment by vskaarthi** [comment]
ok, we just continuing to update our existing site using this theme. The coloring of your theme suited well for some of us. We did not come across one that was sophisticated than this. Do you recommend any of your theme for environmental related non-profits?

**Comment by wpexplorer** [comment]
@vskaarthi Most these these days have all the Customizer settings you need to build a colorful site to your liking. For example our Total theme has TONS of built-in styling options to change everything. We are working on new demos to showcase this soon - https://total.wpexplorer.com/#demos

I've been focused primarily on development and haven't had the time to make nicer new demos, but they will be coming soon ;)
