### ISSUE TITLE
Wordpress 5.8 Upgrade issue

### ISSUE THREAD

**Issue by vskaarthi** [wpexplorer/earth-wordpress-theme#7]
![Earth Theme - Wordpress 5 8 Upgrade issue](https://user-images.githubusercontent.com/39978643/127455487-ab10ae6d-8cdc-42e0-a77b-a4ae7843ebc3.png)

Wordpress 5.8 upgrade breaks the website.

**Comment by wpexplorer** [comment]
@vskaarthi - This error isn't coming from the theme. If you search for the "_excerpt_render_inner_columns_blocks" function mentioned in the error you can see it's no where to be found in the theme.

**Comment by vskaarthi** [comment]
ok, i will take a look at it in detail. Appreciate your response.
